/*
    WITH
    1. 자주 사용/복잡한 쿼리문을 WITH절에 등록
    2. 임시 저장되니 즉시 사용해야함.
    3. 쿼리문의 가독성이 좋아진다.    
*/

-- 1. 고용순서 1~10
-- 1) 서브쿼리
SELECT EMPLOYEE_ID, HIRE_DATE
  FROM (SELECT ROW_NUMBER() OVER(ORDER BY HIRE_DATE) AS RN, EMPLOYEE_ID, HIRE_DATE
          FROM EMPLOYEES)
 WHERE RN BETWEEN 1 AND 10;

-- 2) WITH
WITH
    MY_SUBQUERY AS (
    SELECT ROW_NUMBER() OVER(ORDER BY HIRE_DATE) AS RN, EMPLOYEE_ID, HIRE_DATE
          FROM EMPLOYEES)
SELECT EMPLOYEE_ID, HIRE_DATE
  FROM MY_SUBQUERY
 WHERE RN BETWEEN 1 AND 10;

-- 2. 부서별 부서번호, 부서명, 연봉총액
-- 1) JOIN
SELECT D.DEPARTMENT_ID, 
       D.DEPARTMENT_NAME,
       SUM(E.SALARY)
  FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
 GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME;

-- 2) 서브쿼리
SELECT DEPARTMENT_ID, 
       (SELECT DEPARTMENT_NAME
          FROM DEPARTMENTS D
         WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID) AS DEPT_NAME,
       SUM(SALARY)
  FROM EMPLOYEES E
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;

-- 3) JOIN + 서브쿼리
WITH MY_SUBQUERY AS (
    SELECT DEPARTMENT_ID, SUM(SALARY) AS TOTAL_SALARY
      FROM EMPLOYEES
     GROUP BY DEPARTMENT_ID
)
SELECT MY.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       MY.TOTAL_SALARY
  FROM DEPARTMENTS D INNER JOIN MY_SUBQUERY MY
    ON D.DEPARTMENT_ID = MY.DEPARTMENT_ID;
       