DROP TABLE PROCEEDING_TBL;

DROP TABLE PROJECT_TBL;

DROP TABLE EMPLOYEE_TBL;

DROP TABLE DEPARTMENT_TBL;

-- 부서 테이블
CREATE TABLE DEPARTMENT_TBL (
    DEPT_NO       VARCHAR2(15) NOT NULL,
    DEPT_NAME     VARCHAR2(30),
    DEPT_LOCATION VARCHAR2(50),
    CONSTRAINT PK_DEPT PRIMARY KEY ( DEPT_NO )
);

-- 사원 테이블
CREATE TABLE EMPLOYEE_TBL (
    EMP_NO    NUMBER NOT NULL,
    DEPT_NO   VARCHAR2(15),
    POSITION  CHAR(10),
    NAME      VARCHAR2(15),
    HIRE_DATE DATE,
    SALARY    NUMBER,
    CONSTRAINT PK_EMP PRIMARY KEY ( EMP_NO ),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY ( DEPT_NO )
        REFERENCES DEPARTMENT_TBL ( DEPT_NO )
            ON DELETE SET NULL -- 부서 삭제 -> 해당 부서 정보만 NULL
);

-- 프로젝트 테이블
CREATE TABLE PROJECT_TBL (
    PJT_NO     NUMBER NOT NULL,
    PJT_NAME   VARCHAR2(30),
    BEGIN_DATE DATE,
    END_DATE   DATE,
    CONSTRAINT PK_PJT PRIMARY KEY ( PJT_NO )
);

-- 프로젝트진행 테이블
CREATE TABLE PROCEEDING_TBL (
    PCD_NO    NUMBER NOT NULL,
    EMP_NO    NUMBER NOT NULL,
    PJT_NO    NUMBER NOT NULL,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCD PRIMARY KEY ( PCD_NO ),
    CONSTRAINT FK_PCD_EMP FOREIGN KEY ( EMP_NO )
        REFERENCES EMPLOYEE_TBL ( EMP_NO )
            ON DELETE CASCADE, -- 사원 삭제 -> 해당 프로젝트 진행 삭제
    CONSTRAINT FK_PCD_PJT FOREIGN KEY ( PJT_NO )
        REFERENCES PROJECT_TBL ( PJT_NO )
            ON DELETE CASCADE  -- 프로젝트 삭제 -> 해당 프로젝트 진행 삭제
);