DROP TABLE SCHEDULE_TBL;

DROP TABLE PLAYER_TBL;

DROP TABLE EVENT_TBL;

DROP TABLE NATION_TBL;

CREATE TABLE NATION_TBL (
    N_CODE         NUMBER(3) NOT NULL,
    N_NAME         VARCHAR2(30) NOT NULL,
    N_PARTI_PERSON NUMBER,
    N_PREV_BANK    NUMBER,
    N_CURR_BANK    NUMBER
);

CREATE TABLE EVENT_TBL (
    E_CODE       NUMBER NOT NULL,
    E_NAME       VARCHAR2(30) NOT NULL,
    E_FIRST_YEAR NUMBER(4),
    E_INFO       VARCHAR2(100)
);

CREATE TABLE PLAYER_TBL (
    P_CODE NUMBER(3) NOT NULL,
    P_NAME VARCHAR2(30) NOT NULL,
    N_CODE NUMBER(3) NOT NULL,
    E_CODE NUMBER NOT NULL,
    P_BANK NUMBER,
    P_AGE  NUMBER(3)
);

CREATE TABLE SCHEDULE_TBL (
    S_NO         NUMBER(3) NOT NULL,
    N_CODE       NUMBER(3),
    E_CODE       NUMBER,
    S_START_DATE DATE,
    S_END_DATE   DATE,
    S_INFO       VARCHAR2(100)
);

ALTER TABLE NATION_TBL ADD CONSTRAINT PK_N PRIMARY KEY ( N_CODE );

ALTER TABLE EVENT_TBL ADD CONSTRAINT PK_E PRIMARY KEY ( E_CODE );

ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_P PRIMARY KEY ( P_CODE );

ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_S PRIMARY KEY ( S_NO );

ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_N_P FOREIGN KEY ( N_CODE )
        REFERENCES NATION_TBL ( N_CODE )
            ON DELETE CASCADE;

ALTER TABLE PLAYER_TBL
    ADD CONSTRAINT FK_E_P FOREIGN KEY ( E_CODE )
        REFERENCES EVENT_TBL ( E_CODE )
            ON DELETE CASCADE;

ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT FK_N_S FOREIGN KEY ( N_CODE )
        REFERENCES NATION_TBL ( N_CODE )
            ON DELETE SET NULL;

ALTER TABLE SCHEDULE_TBL
    ADD CONSTRAINT FK_E_S FOREIGN KEY ( E_CODE )
        REFERENCES EVENT_TBL ( E_CODE )
            ON DELETE SET NULL;

-- 국가 테이블 기본키 삭제 (기본키를 참조하는 외래키 먼저 삭제)
ALTER TABLE PLAYER_TBL DROP CONSTRAINT FK_N_P;
ALTER TABLE SCHEDULE_TBL DROP CONSTRAINT FK_N_S;
ALTER TABLE NATION_TBL DROP CONSTRAINT PK_N;

-- 선수 테이블 FK_E_P 일시중지
ALTER TABLE PLAYER_TBL DISABLE CONSTRAINT FK_E_P;

-- 활성화
ALTER TABLE PLAYER_TBL ENABLE CONSTRAINT FK_E_P;