-- 1. 사원 테이블에서 FIRST_NAME, LAST_NAME 조회
SELECT E.FIRST_NAME AS 이름, E.LAST_NAME AS 성
  FROM EMPLOYEES E;
  
-- 2. 사원테이블에서 아이디 중복 제거하고 조회
SELECT DISTINCT DEPARTMENT_ID
  FROM EMPLOYEES;

-- 3. 사원테이블 EMPLOYEE_ID가 150인 사원 조회
SELECT *
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 150;
 
 -- 4. 사원테이블 연봉이 10000 이상인 사원 조회
SELECT *
  FROM EMPLOYEES 
 WHERE SALARY >= 10000;
 
 -- 5. 사원테이블 연봉이 10000 이상, 20000 이하인 사원 조회
SELECT *
  FROM EMPLOYEES 
 WHERE SALARY >= 10000 AND SALARY <= 20000;
 --    SALARY BETWEEN 10000 AND 20000;
 
-- 6. 사원테이블 부서번호가 30, 40, 50인 사원 조회
SELECT *
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID IN(30, 40, 50);
 
-- 7. 사원테이블 부서번호가 없는 사원 조회
SELECT *
  FROM EMPLOYEES 
 WHERE DEPARTMENT_ID IS NULL;
 
-- 8. 사원테이블 커미션 받는 사원 조회
SELECT *
  FROM EMPLOYEES 
 WHERE COMMISSION_PCT IS NOT NULL;
 
-- 9. 515로 시작하는 전화번호를 가진 사원 조회
SELECT *
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515' || '%';

-- 10. 515로 시작하는 전화번호 조회 (중복제거)
SELECT DISTINCT PHONE_NUMBER
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515' || '%';
 
-- 11.연봉순으로 조회
SELECT *
  FROM EMPLOYEES
 ORDER BY SALARY ASC; -- 기본값: 오름차순

SELECT *
  FROM EMPLOYEES
 ORDER BY SALARY DESC; -- 내림차순
 
-- 12. 입사순 조회
SELECT *
  FROM EMPLOYEES
 ORDER BY HIRE_DATE ASC;
 
-- 13. 부서별로 연봉순
SELECT *
  FROM EMPLOYEES
 ORDER BY DEPARTMENT_ID, SALARY DESC;
